#!/bin/bash

users='[
	{"user":"Azorro"},
	{"user":"Atonza","email":"sum@avg.org"},
	{"user":"Agozga"},
	{"user":"Aqondo"},
	{"user":"Asalora"},
	{"user":"Azizigopx"}
]' 

db='[
	{"name":"AAAZZ"},{"name":"AAAZZ1"}
]' 

#cfg template
cfgx='{
	"wait":60,"remote":true,"hub":"http://localhost:4444/wd/hub"
'

url='rdvmden120 rdvmden53 rdvmva81 rdvmden14 rdvmden40'
browser='chrome firefox ie chrome firefox'

url='rdvmden28'
browser='firefox'

export db users; echo users=$users db=$db

SECONDS=0; s=0; p=0; f=-1;  browser=($browser)

for u in $url; do	#kick tests parallel for urls all over the browsers
	b=${browser[$bi]}
	cfg="$cfgx,\"url\":\"http://$u:8585\",\"browser\":\"$b\"}"
	bi=$((++i%${#browser[*]}))
	echo cfg=$cfg
	export cfg
	(python demo.py; s=$?; echo $u on $b ret $s took $SECONDS; exit $s)&

done

while test $(jobs|wc -l) -gt 0; do
	wait -n; s=$?; test $s -eq 0 -a $s != 127 && ((p++)) || ((f++))

done

echo $p pass, $f fail, took $SECONDS

