#!/bin/bash

usage='
	 hub install		install and exit
	 hub 			install and run hub + local node
	 hub [hub|node]		install and run hub or node alone
	 hub node [host:port]	install and run node pointed to remote host:port hub

	  env var: [host]	define host/ip for the node (may be needed on vpn)
'
#log cleanup
#(while true; do (date; echo cleanup chromedriver logs; find /cygdrive/d/tmp -mtime +2|xargs rm -rf)& sleep 1d; done)&

mkdir -p drivers
cd drivers

host=${host:-$(hostname -i|grep -o '10.130[^ ]*')} #vpn/intranet
host=${host:-$HOSTNAME} #home

#browser cap opts
cmd /c ver|grep 'Version 10'
if [ $? = 0 ]; then
   EDGE_DRV="-Dwebdriver.edge.driver=$(cygpath -m $(pwd))/MicrosoftWebDriver.exe"
   TWEAK_CAP=("-browser" "browserName=internet explorer,maxInstances=1"
   "-browser" "browserName=MicrosoftEdge,platform=WINDOWS,maxInstances=5")
else
   TWEAK_CAP=(
   "-browser" "browserName=firefox,version=53,maxInstances=5,firefox_binary=c:\Users\Administrator\Downloads\drivers\firefox53\firefox.exe"
   "-browser" "browserName=firefox,version=50.0.1,maxInstances=5,firefox_binary=c:/browsers/firefox/50.0.1/firefox.exe"
   "-browser" "browserName=chrome,maxInstances=5"
   "-browser" "browserName=Xinternet explorer,maxInstances=1"
   )
fi

trap 'kill -9 $(cat hpid) 2>/dev/null; cd -' INT TERM ERR

ss="selenium-server-*"

#test -f $ss || wget -c --trust-server-names https://goo.gl/Lyo36k
v=3.6.0 #3.6.0 3.5.0 3.4.0
test -f $ss || wget http://selenium-release.storage.googleapis.com/${v::3}/selenium-server-standalone-$v.jar

test -f geckodriver.exe || {
	 v=0.16.1 #0.16.1 - ff53 0.19.0 - ff56
	wget -c https://github.com/mozilla/geckodriver/releases/download/v$v/geckodriver-v$v-win64.zip
	jar -xvf geckodriver-v$v-win64.zip || { echo  "unzip error, check bin/jar is in PATH"; kill -TERM $$; }
}
test -f chromedriver.exe || {
	 v=2.33 #2.29 2.33
	wget -c http://chromedriver.storage.googleapis.com/$v/chromedriver_win32.zip
	jar -xvf chromedriver_win32.zip
}
test -f IEDriverServer.exe || {
	 v=3.6.0 #3.4.0 3.6.0
	wget -c http://selenium-release.storage.googleapis.com/${v::3}/IEDriverServer_Win32_$v.zip
	jar -xvf IEDriverServer_Win32_$v.zip
}
test -f MicrosoftWebDriver.exe || {
	#r14393
	wget -c https://download.microsoft.com/download/3/2/D/32D3E464-F2EF-490F-841B-05D53C848D15/MicrosoftWebDriver.exe
	#r15063
	#wget -c https://download.microsoft.com/download/3/4/2/342316D7-EBE0-4F10-ABA2-AE8E0CDF36DD/MicrosoftWebDriver.exe
	#edge v15 wget -c https://download.microsoft.com/download/3/4/2/342316D7-EBE0-4F10-ABA2-AE8E0CDF36DD/MicrosoftWebDriver.exe
}

chmod 755 *.exe

test "$1" = install && exit

test ${1:-hub} = hub && { java -jar $ss -role hub -timeout 70 & echo $!>hpid; }
test ${1:-node} = node && { java $EDGE_DRV -jar $ss -role node -timeout 70 -port 5554 -hub http://${2:-localhost:4444}/grid/register -host $host -maxSession 10 "${TWEAK_CAP[@]}" & echo $!>>hpid; }
#-browser browserName=firefox,maxInstances=10
wait -n || kill -TERM $$

#instructions: https://github.com/SeleniumHQ/selenium/wiki/Grid5

#examples:

	#-browser browserName=firefox,version=3.6,maxInstances=5,platform=LINUX
	#-browser browserName=firefox,version=3.6,firefox_binary=/home/myhomedir/firefox36/firefox,maxInstances=3,platform=LINUX -browser browserName=firefox,version=4,firefox_binary=/home/myhomedir/firefox4/firefox,maxInstances=4,platform=LINUX
	#-browser “browserName=firefox,version=3.6,firefox_binary=c:\Program Files\firefox ,maxInstances=3, platform=WINDOWS”
	#By default, starting the node allows for concurrent use of 11 browsers... : 5 Firefox, 5 Chrome, 1 Internet Explorer. The maximum number of concurrent tests is set to 5 by default. To change this and other browser settings, you can pass in parameters to each -browser switch (each switch represents a node based on your parameters). If you use the -browser parameter, the default browsers will be ignored and only what you specify command line will be used.
	#-registerCycle N = how often in ms the node will try to register itself again.Allow to restart the hub without having to restart the nodes.

	#Really large (>50 node) Hub installations may need to increase the jetty threads by setting -DPOOL_MAX=512 (or larger) on the java command line.

	#Optional:

	#-port [4444]
	#-host [localhost]
	#-timeout [300s] - hub releases node w/o any requests
	#-maxSession [5] - max n all kinds of  browsers run parallel

