#!/bin/bash

#install py and selenium from source on rhel or centos
V=3.6.1 #3.5.2

test "$USER" = root || { echo error: run as root; exit 1; }
yum install gcc zlib-devel bzip2-devel sqlite sqlite-devel openssl-devel
cd /usr/src
wget https://www.python.org/ftp/python/$V/Python-$V.tgz -O - | tar -zx
cd Python-$V
./configure
make altinstall
rm -rf /usr/local/bin/python
ln -s /usr/local/bin/python${V:0:3} /usr/local/bin/python
python -V | grep $V || { echo error: wrong py version in path; exit 1; }
python -m pip install selenium && echo success

grep PYTHONPATH= ~/.bashrc >/dev/null || echo export PYTHONPATH=src >> ~/.bashrc

#clone pyselenium and friendly projects
cd; for r in bvtlite pyselenium confbucket binbucket; do
 git clone http://dkrukov@irepo.eur.ad.sag/scm/~dkrukov/$r.git
done


