#!/bin/bash

set -e #strict on error

#install python from source and selenium module on rhel or centos
V=3.6.1 #3.5.2
S=3.5.0 #selenium module

test "$USER" = root || { echo error: run as root; false; }

yum install gcc zlib-devel bzip2-devel sqlite sqlite-devel openssl-devel

#( cd /usr/src
#wget https://www.python.org/ftp/python/$V/Python-$V.tgz -O - | tar -zx
#cd Python-$V
#./configure
#make altinstall
#)

#link switch breaks e.g yum and other 2.7 python dependent system stuff
#for l in /usr/{,local}/bin/python
#do
##rm -rf $l
##ln -s /usr/local/bin/python${V:0:3} $l
#done

/usr/local/bin/python${V:0:3} -V | grep $V || { echo error: python $V fail check; false; }
/usr/local/bin/python${V:0:3} -m pip install selenium==$S

cd .. #go home

grep PYTHONPATH= .bashrc || echo export PYTHONPATH=src >> .bashrc
#export funct to access python command instead of sym links
grep 'function python' .bashrc || echo "
function python () {
/usr/local/bin/python${V:0:3} \$@
}
declare -fx python
" >> .bashrc

#clone pyselenium and friendly projects
for r in bvtlite pyselenium confbucket; do
 git clone https://github.com/dan-kruk/pyselenium.git ||:
done

echo "
	completed OK
"
