#!/bin/bash

export PYTHONIOENCODING=utf-8
export JENKINS_URL=fakeone
#export LOGS=c:/tmp/junit
SECONDS=0

bs='edge'
remote=true

export login='{"url":"http://rdvmden103:8585","Xusername":"dkrukov","Xpassword":"dkrukov"}'


#t=t/mws/ccs/toggle_saml_dls.py
#t=t/mws/dls/checkprocs.py
#t=t/mws/dls/toggle.py
#t=t/mws/examples/feature.py
t=t/mws/processanalytics/test.py
#t=t/mws/rootcontext/chroot.py
#t=t/test.py
#t=t/unit/tc.py

for b in $bs; do
 export cfg="{ 'capabilities':{'platform':'ANY'},'Xwait':20,'remote':$remote,'hub':'http://usvardvmden141:4444/wd/hub','browser':'$b'}"
 (python -u $t | tee /tmp/slog; echo $b $? done $SECONDS)&
done

wait

echo took $SECONDS

